server {
  listen 443 ssl;
  server_name adminpanel.tesc.farm;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;
  ssl_certificate /etc/letsencrypt/live/adminpanel.tesc.farm/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/adminpanel.tesc.farm/privkey.pem;
  root /srv/www/adminpanel.tesc.farm;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
}
server {
  listen 80;
  server_name adminpanel.tesc.farm;
  return 301 https://adminpanel.tesc.farm$request_uri;
}
