CREATE TABLE `areas` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`description` text,`use` text);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX `idx_areas_deleted_at` ON `areas`(`deleted_at`);
CREATE TABLE `crops` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`variety` text,`notes` text);
CREATE INDEX `idx_crops_deleted_at` ON `crops`(`deleted_at`);
CREATE TABLE `beds` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`area_id` integer,`notes` text,CONSTRAINT `fk_beds_area` FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`));
CREATE INDEX `idx_beds_deleted_at` ON `beds`(`deleted_at`);
CREATE TABLE `plantings` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`crop_id` integer,`bed_id` integer,`notes` text,CONSTRAINT `fk_plantings_crop` FOREIGN KEY (`crop_id`) REFERENCES `crops`(`id`),CONSTRAINT `fk_plantings_bed` FOREIGN KEY (`bed_id`) REFERENCES `beds`(`id`));
CREATE INDEX `idx_plantings_deleted_at` ON `plantings`(`deleted_at`);
CREATE TABLE `harvests` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`weight` real,`bin` text,`crop_id` integer,`bed_id` integer,CONSTRAINT `fk_harvests_crop` FOREIGN KEY (`crop_id`) REFERENCES `crops`(`id`),CONSTRAINT `fk_harvests_bed` FOREIGN KEY (`bed_id`) REFERENCES `beds`(`id`));
CREATE INDEX `idx_harvests_deleted_at` ON `harvests`(`deleted_at`);
CREATE TABLE `products` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`type` text,`unit` text,`price` integer,`quantity` integer,`weight` integer,`length` integer,`width` integer,`height` integer);
CREATE INDEX `idx_products_deleted_at` ON `products`(`deleted_at`);
CREATE TABLE `processes` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`unit` text,`quantity` integer,`weight` real,`cull` real,`student_use` real,`value_added` real,`harvest_id` integer,`product_id` integer,CONSTRAINT `fk_processes_harvest` FOREIGN KEY (`harvest_id`) REFERENCES `harvests`(`id`),CONSTRAINT `fk_processes_product` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`));
CREATE INDEX `idx_processes_deleted_at` ON `processes`(`deleted_at`);
CREATE TABLE `tasks` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`description` text,`type` text,`barcode` text,`area_id` integer,`planting_id` integer,`harvest_id` integer,`process_id` integer,CONSTRAINT `fk_tasks_harvest` FOREIGN KEY (`harvest_id`) REFERENCES `harvests`(`id`),CONSTRAINT `fk_tasks_process` FOREIGN KEY (`process_id`) REFERENCES `processes`(`id`),CONSTRAINT `fk_tasks_area` FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`),CONSTRAINT `fk_tasks_planting` FOREIGN KEY (`planting_id`) REFERENCES `plantings`(`id`));
CREATE INDEX `idx_tasks_deleted_at` ON `tasks`(`deleted_at`);
CREATE TABLE `workers` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`barcode` text);
CREATE INDEX `idx_workers_deleted_at` ON `workers`(`deleted_at`);
CREATE TABLE `hours` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`start` datetime,`duration` real,`department` text,`task_id` integer,`worker_id` integer, `notes` text,CONSTRAINT `fk_hours_task` FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`),CONSTRAINT `fk_hours_worker` FOREIGN KEY (`worker_id`) REFERENCES `workers`(`id`));
CREATE INDEX `idx_hours_deleted_at` ON `hours`(`deleted_at`);
CREATE TABLE `tags` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text);
CREATE INDEX `idx_tags_deleted_at` ON `tags`(`deleted_at`);
CREATE TABLE `task_tags` (`task_id` integer,`tag_id` integer,PRIMARY KEY (`task_id`,`tag_id`),CONSTRAINT `fk_task_tags_task` FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`),CONSTRAINT `fk_task_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`));
CREATE TABLE `crop_tags` (`crop_id` integer,`tag_id` integer,PRIMARY KEY (`crop_id`,`tag_id`),CONSTRAINT `fk_crop_tags_crop` FOREIGN KEY (`crop_id`) REFERENCES `crops`(`id`),CONSTRAINT `fk_crop_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`));
CREATE TABLE `sales` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`type` text,`quantity` integer,`price` integer,`tax` integer,`total` integer,`product_id` integer,CONSTRAINT `fk_sales_product` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`));
CREATE INDEX `idx_sales_deleted_at` ON `sales`(`deleted_at`);
