/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MicrosoftSins: typeof import('./components/MicrosoftSins.vue')['default']
    PetitionForm: typeof import('./components/PetitionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/SiteHeader.vue')['default']
  }
}
