/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterSearch: typeof import('./components/FilterSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/SettingsButton.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskSelector: typeof import('./components/TaskSelector.vue')['default']
  }
}
