/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/area/': RouteRecordInfo<
      '/area/',
      '/area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/area/[id]': RouteRecordInfo<
      '/area/[id]',
      '/area/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/area/builder': RouteRecordInfo<
      '/area/builder',
      '/area/builder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cropbuilder': RouteRecordInfo<
      '/cropbuilder',
      '/cropbuilder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mobile': RouteRecordInfo<
      '/mobile',
      '/mobile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/taskbuilder': RouteRecordInfo<
      '/taskbuilder',
      '/taskbuilder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/area/index.vue': {
      routes:
        | '/area/'
      views:
        | never
    }
    'src/pages/area/[id].vue': {
      routes:
        | '/area/[id]'
      views:
        | never
    }
    'src/pages/area/builder.vue': {
      routes:
        | '/area/builder'
      views:
        | never
    }
    'src/pages/cropbuilder.vue': {
      routes:
        | '/cropbuilder'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/mobile.vue': {
      routes:
        | '/mobile'
      views:
        | never
    }
    'src/pages/taskbuilder.vue': {
      routes:
        | '/taskbuilder'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
