/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/area/': RouteRecordInfo<'/area/', '/area', Record<never, never>, Record<never, never>>,
    '/area/[id]': RouteRecordInfo<'/area/[id]', '/area/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/area/builder': RouteRecordInfo<'/area/builder', '/area/builder', Record<never, never>, Record<never, never>>,
    '/cropbuilder': RouteRecordInfo<'/cropbuilder', '/cropbuilder', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mobile': RouteRecordInfo<'/mobile', '/mobile', Record<never, never>, Record<never, never>>,
    '/taskbuilder': RouteRecordInfo<'/taskbuilder', '/taskbuilder', Record<never, never>, Record<never, never>>,
  }
}
