DBCONN: ENC[AES256_GCM,data:oFLRXUbymA==,iv:QsOxKJ474866yHkB9nZDuhWYge7JsXjrwxX3czpiOls=,tag:CWe1T8/UV2PonUVhhTaImA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeEJEK0JodERPNG1GZldn
            SmdRTXNsL2ppZGRGekpwdjdRYnp6NzVGTFNBCll0cUw0WTNBR0dKNU9jQTFocXo4
            VElFc1gzMUE0RmRaS0FyMCtOeTRRUUkKLS0tIElyZTJqdENyUFRaL1k4VVBSTUs1
            WGtWWlVpMGd3U0l0bXdud0JZcTd6eW8Ki/Ylsw/ttnm/ZxBvHzFkQq6kG7TXaw4z
            vmLymxWMzYu1OaOeJzp+QiwbOE3YmZFNKQrqdAX+hQTMDEigEsMjgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T08:08:06Z"
    mac: ENC[AES256_GCM,data:sohwASwd9vFZKLeq6FC5zB9NXOfqG6Z1xi8kZBpK1R75UDfNqStom0h9BODWgyVPgvEcApK36qRult8kaWJvMxVcOO363MdnVPKECkDTOw2YUuiVWrEK7T4KpN3dmWcvudtTSR5CmFFoWPBpvSk35j3v2w68Ei7xXF7UrkDJ9ys=,iv:H4jY80pENWLKBXvRGpNT4d7Vd1CnfyafFQieP9k3dQI=,tag:2J202Yn/Anr58DsLjQIUbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
