DBCONN: ENC[AES256_GCM,data:pO7LkQzhn4Hf3lxJfic=,iv:oErNHmYVCJWB4AthRsvHW3K3naW9ohQcinTqJ9EXh8o=,tag:5xALGQ1Jjyl5HBzEF4dBAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRUxRdmNIVmJObXJybjRr
            OWxLOUwvSERMbW1JTUtjaTJoOHRIM0tMM2c4CkxVNEtlNnkwNjl0bGpFWXBjVDBQ
            Rk5SdEV3SUdIcHdwcUR2dHJmKzlLMzQKLS0tIDh0Z1RrQU5tTG5lT05oSW1VcFFE
            SVhPNWVnZE04MDFMZDI5emE2Qm83UkUKtSnXHW8FW+M6qxLN5r3VMMgs23/1yIHE
            qlJ60S5EhxhrU1pPg/5m8pxeauHC5dslhQtovhIxk7JouIDpTPz+gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NmF5RkZ0THpDeUFqUGYz
            OTF4bXk5eEtpRXc4TlZ2aXlNWXAvaSsyL1NJCkhiVjBzamVCMmtZRkNQaTBSK0dM
            MGNxMm9xRmdBMHRnSEU2UDhueVNVOFkKLS0tIGlKRThjekhyeTBYY0V3WE5ud25n
            VGRIeDhxbGZHYXN3WnJvaTRHTUt5MkUKklCYWsouYeVHvXcV45iEw1O+uMaxR3VU
            BzxZInBDSlEKUD3oG6LTLRlJQYXTu18A3GHcpRTzWqUkOocssI3MGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T21:00:03Z"
    mac: ENC[AES256_GCM,data:3/8/0UJxoirACFM2eTIsUvbz5oj30NtHbSMJTkzcQurjRsJbnnlAItOUt6q6c9s8mxzPsO57aShsosB1OYvyT3Vd5ua0X2CFG7LP0o0VFduxLLZ/O8ASv12Tl92P07nAx3vGh3z778QyiwEHDVPbiLstEaDI4jP3IfNDvztftbU=,iv:zpwXc7ekvNELzQmfbIx19imB0L2+ToCJrfxIE3fQHLo=,tag:k3yUqphnLm64IgEFc/+62w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
