PRODDBCONN: ENC[AES256_GCM,data:wFs/tiWTCnEhQ8MHsw0=,iv:Mqx6EDySgPvgFgAGkXPVsyxn1M0U1tNrAF/o+AqUxTQ=,tag:dM+Ng8cfdvBmw2Q2Nm9NoQ==,type:str]
DEVDBCONN: ENC[AES256_GCM,data:3tPfyEr0F1gAKOcgu+ODpF68,iv:hXAks7BCMPmYVLp7zbJO8rB5PzcMrAH6V9iHFMGX9VI=,tag:HbI2kz+IUSiwCTRJWTJa1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydUlSRzZXdnhEUC9mSmlE
            ajUzaUlWWkhKVU9vNWlYbGYzWUVTcitDQUIwCkF1QjNPMEMxMzBzRzZ6THh5SkxB
            eEREWUZJRkthdGdIUmpiaGUyM0hMQTgKLS0tIEVreW9mWGV1aFRtRm1za1BDOGNl
            SFNvcnBETjlRc05vN0l0bndCdUhOeE0Kr/cY9k7ivxDir2/aVk3Q1cvdKYzZHTAS
            efn4clhlhtHOqIz9ArzzjkHA/VZoWyG+A06WuDvM9tD9eqh+yJmWDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNGtwekZ6cmV5a2dwaUdQ
            bGZaeWE0SnZTc3BhL3RVNFYrb3c0aVBFN25NCmxOL0Yyb0ZHVlNRdWxjbFd2NmRu
            OXkvOVUzVTluUS81VUJqSWw1SUpuWFUKLS0tIEJkemExbE9nQ2lpaXRhdHZPNVJq
            OVFnRkQzbHovSEFJQzhmRi9tUWh3SVEKERQhVmYHKymmRmOQ9pUatDBlowhxeSgJ
            FVmUE92q4Aq19PCWj/L/U7Jjex9ntKSMdWMJ5lxuPmb6v7JjoNaMkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lz7h0qpn7eyqfunplwqrxs0etk0z6ew74lvasczw7hr7tttv45fseema0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdGZiQmxZb0FGOVlkQ2Ni
            MlAraktuMEpLWVEyamllQmRXSndOb0pFclN3CmJMOEpmYk1uSE5IR044cUZEOXMr
            Snc5UFEyblpFWnVBakk3NEZ4czFBbVkKLS0tIGJGSGw5SVFNeHl4Um1sb1ZkaFZD
            TlJHOXJuNWJta1I1eStXdDBnMTREbWsK5WBVxVn35DuZeFS+BWEdZhRGX7Z0XRsL
            rWWd6wdl2/DmohICBzFArm5d3Pj10oiELL7F429b+oStc9Xgcd2NcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:00:31Z"
    mac: ENC[AES256_GCM,data:MOKJTyBmby5/d5Ps+rA8V4pj04L8N/tjsFOgF83XHQ/iGfP8OvU9WAM3dwmo6sMEcrYqfiOLAIGMQuFAa9V2DpwcBAdnMRnMp6hJ7g1u1gr/T3NLI9QFhqf8VwduopoftwLtDwWok+oR7I7km7NOf+k/L8F+kaLGgiBHAkIOPSI=,iv:/73giUYT0+fHChfZLA/Er06ZIzQ/RkBK50I0+nQ1Sx4=,tag:Hw0JKHmgKI49QDNuXi1fEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
