PRODDBCONN: ENC[AES256_GCM,data:wFs/tiWTCnEhQ8MHsw0=,iv:Mqx6EDySgPvgFgAGkXPVsyxn1M0U1tNrAF/o+AqUxTQ=,tag:dM+Ng8cfdvBmw2Q2Nm9NoQ==,type:str]
DEVDBCONN: ENC[AES256_GCM,data:c4+V0xSEkqHNzLM3cEg=,iv:7qQnVGM+p8UdZC3Qb3CKk3ptp73uymDBjUh5I3uKAmI=,tag:78E0V3ujYpGKtjRYv4G+EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRUxRdmNIVmJObXJybjRr
            OWxLOUwvSERMbW1JTUtjaTJoOHRIM0tMM2c4CkxVNEtlNnkwNjl0bGpFWXBjVDBQ
            Rk5SdEV3SUdIcHdwcUR2dHJmKzlLMzQKLS0tIDh0Z1RrQU5tTG5lT05oSW1VcFFE
            SVhPNWVnZE04MDFMZDI5emE2Qm83UkUKtSnXHW8FW+M6qxLN5r3VMMgs23/1yIHE
            qlJ60S5EhxhrU1pPg/5m8pxeauHC5dslhQtovhIxk7JouIDpTPz+gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NmF5RkZ0THpDeUFqUGYz
            OTF4bXk5eEtpRXc4TlZ2aXlNWXAvaSsyL1NJCkhiVjBzamVCMmtZRkNQaTBSK0dM
            MGNxMm9xRmdBMHRnSEU2UDhueVNVOFkKLS0tIGlKRThjekhyeTBYY0V3WE5ud25n
            VGRIeDhxbGZHYXN3WnJvaTRHTUt5MkUKklCYWsouYeVHvXcV45iEw1O+uMaxR3VU
            BzxZInBDSlEKUD3oG6LTLRlJQYXTu18A3GHcpRTzWqUkOocssI3MGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T04:41:36Z"
    mac: ENC[AES256_GCM,data:iJx4gD0MMawq+kaFasch2l2/lSS78iAtKp2yDV0R9pgjYkQ9HTneBYoVSXGmzl1Wj5BZg4RHfxBZpPm7vXBlZAgkZEOFqzMQIGJre0ex8czIil8EDqR/Cehpr3gduZjBzcN6sLtuhFuFI9GhNzP9SJ+OsmbklS3EEbRo1Ymgxqk=,iv:TaDsGHGE7YYRxCiUIbQW3hBEJj+ATQUS4FkWCVJwrg0=,tag:q8vPaRB2RVihu2QDuE59UA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
