creation_rules:
  # Keys: Shawn tablet, Shawn desktop
  - age: >-
      age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0,
      age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq,
      age1lz7h0qpn7eyqfunplwqrxs0etk0z6ew74lvasczw7hr7tttv45fseema0t
