creation_rules:
  # Keys: Shawn Desktop, Shawn MacBook, Evergreen Server
  - age: >-
      age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq,
      age1m2uc556t8f0su9m35ssa0m9qxkmk9x8dzx6a76qvxmnf6kwd55zqnxfs2g,
      age102lkl5pfcrt47hur7p8424vkflzqfrjvdt0psglhyd2g3qpax3tsfdyzur
