creation_rules:
  # Keys: Shawn tablet, Shawn desktop, SBE Server, Shawn MacBook, Hayden
  - age: >-
      age1x76dhjjs8azxlj3pm05s0g2t7j8egfsk20j7aj7tg5derwdfpcjsm4ukq0,
      age12wsgmm80wwqfq7cdt0vx27hllmm0f0nls7scjs88yfk66e658v6qr6xeqq,
      age1lz7h0qpn7eyqfunplwqrxs0etk0z6ew74lvasczw7hr7tttv45fseema0t,
      age1m2uc556t8f0su9m35ssa0m9qxkmk9x8dzx6a76qvxmnf6kwd55zqnxfs2g,
      age1969dm92af0pjf746ltnp6uujvjj5zr5vv8a9qfgjv2f6f3azyugqlahw3a
